### ISSUE TITLE
forge start failed

### ISSUE THREAD

**Issue by tyrchen** [ArcBlock/forge-cli#226] opened 2019-09-16 22:45 UTC
If run `forge status` right after installed forge-cli, an error will occur and later on do `forge init` would just download one tarball and `forge start` failed.

```
[centos@token-swap ~]$ forge status
✔ initialized tmp dir for forge-cli: /home/centos/.forge_cli/tmp
✔ initialized bin dir for forge-cli: /home/centos/.forge_cli/bin
✔ initialized cache dir for forge-cli: /home/centos/.forge_cli/cache
✔ initialized logs dir for forge-cli: /home/centos/.forge_cli/logs
✔ initialized release dir for forge-cli: /home/centos/.forge_cli/release
✔ Checking new version...
✖ config file /home/centos/.forge_cli/release/forge/release.yml invalid
[centos@token-swap ~]$ forge init
ℹ Detected platform is: centos
✔ Latest forge release version: v0.37.7

██████╗ ██╗   ██╗     █████╗ ██████╗  ██████╗██████╗ ██╗      ██████╗  ██████╗██╗  ██╗
██╔══██╗╚██╗ ██╔╝    ██╔══██╗██╔══██╗██╔════╝██╔══██╗██║     ██╔═══██╗██╔════╝██║ ██╔╝
██████╔╝ ╚████╔╝     ███████║██████╔╝██║     ██████╔╝██║     ██║   ██║██║     █████╔╝
██╔══██╗  ╚██╔╝      ██╔══██║██╔══██╗██║     ██╔══██╗██║     ██║   ██║██║     ██╔═██╗
██████╔╝   ██║       ██║  ██║██║  ██║╚██████╗██████╔╝███████╗╚██████╔╝╚██████╗██║  ██╗
╚═════╝    ╚═╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═════╝ ╚══════╝ ╚═════╝  ╚═════╝╚═╝  ╚═╝

ℹ Start download https://releases.arcblock.io/forge/0.37.7/forge_centos_amd64.tgz
ℹ Downloading forge_centos_amd64.tgz |████████████████████████████████████████ 100% || 22.80/22.B
[centos@token-swap ~]$ forge start
✖ config file /home/centos/.forge_cli/release/forge/release.yml invalid
```

**Comment by wangshijun** [comment] 2019-09-19 06:58
should be fixed in #225

**Comment by wangshijun** [comment] 2019-09-19 06:58
the issue is caused by forge-cli exit on an non-exist `release.yml`

**Comment by wangshijun** [comment] 2019-09-19 06:58
the issue is caused by forge-cli exit on an non-exist `release.yml`

**Closed as completed** 2019-09-19 07:41 UTC
